name: test
on:
  push: {}
  pull_request:
    paths-ignore:
      - docs/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: debianmaster/actions-k3s@v1.0.5
        with:
          version: 'v1.23.6-k3s1'
      - run: make setup-ci-env
      - run: make validate-ci
      - run: make validate
      - run: make build
      - run: make test
